version: '3.8'

services:
  entry:
    image: nginx:alpine
    depends_on:
      - provider-entry
    ports:
      - 8080:8080
      - 9090:9090
    networks:
      - app-net
    volumes:
      - ./hack/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./tmp/entry:/certs

  provider-entry:
    image: ghcr.io/wirepact/contract-provider:1-latest
    user: root
    depends_on:
      - repo
      - pki-main
    environment:
      - DEBUG=true
      - COMMON_NAME=provider-entry
      - PKI_ADDRESS=http://pki-main:8080
      - REPO_ADDRESS=http://repo:9000
      - REPO_API_KEY=foobar
    networks:
      - app-net
    volumes:
      - ./tmp/entry:/app/data

  repo:
    image: ghcr.io/wirepact/contract-api:1-latest
    environment:
      - DEBUG=true
      - PORT=9000
      - API_KEY=foobar
    networks:
      - app-net
    volumes:
      - ./tmp/repo:/app/data/contracts

  repo-gui:
    image: ghcr.io/wirepact/contract-gui:1-latest
    environment:
      - DEBUG=true
      - PORT=9090
      - REPO_HOST=http://repo:9000
      - REPO_API_KEY=foobar
    networks:
      - app-net

  pki-main:
    image: ghcr.io/wirepact/k8s-pki:2.4.0
    environment:
      - DEBUG=true
      - PORT=8080
      - LOCAL=true
    networks:
      - app-net
    volumes:
      - ./tmp/pki_main:/app/ca

  app:
    image: ghcr.io/wirepact/demo-applications/basic-auth-backend-app:latest
    depends_on:
      - provider-app
    entrypoint: ''
    command: sh -c "update-ca-certificates && dotnet /app/BasicAuthApp.dll"
    environment:
      # - HTTP_PROXY=http://envoy-app:8500
      - HTTPS_PROXY=https://envoy-app:8500
      - LOGGING__LOGLEVEL__DEFAULT=Debug
      - LOGGING__LOGLEVEL__MICROSOFT.ASPNETCORE=Debug
      - PORT=8001
      - AUTH_USER=admin
      - AUTH_PASS=supersecret
      - API_URL=https://envoy-api:9000/swapi/people
    networks:
      - app-net
    volumes:
      - ./tmp/app/ca.crt:/usr/local/share/ca-certificates/ca.crt
      - ./tmp/app:/certs

  envoy-app:
    image: envoyproxy/envoy:v1.23-latest
    depends_on:
      - provider-app
    command: envoy -c /etc/envoy/envoy.yaml --component-log-level connection:trace,ext_authz:debug,conn_handler:debug,forward_proxy:debug,http:debug,matcher:debug,router:debug
    volumes:
      - ./hack/envoy-config.app.yaml:/etc/envoy/envoy.yaml:ro
      - ./tmp/app:/certs
      - ./tmp/app/chain.crt:/usr/local/share/ca-certificates/chain.crt
    networks:
      - app-net

  translator-app:
    image: ghcr.io/wirepact/k8s-basic-auth-translator:2.0.31
    depends_on:
      - pki-main
    volumes:
      - ./hack/test-repository.csv:/test-repository.csv:ro
    environment:
      - PKI_ADDRESS=http://pki-main:8080
      - NAME=translator-app
      - DEBUG=true
      - CSV_PATH=/test-repository.csv
    networks:
      - app-net

  provider-app:
    image: ghcr.io/wirepact/contract-provider:1-latest
    user: root
    depends_on:
      - repo
      - pki-main
    environment:
      - DEBUG=true
      - COMMON_NAME=envoy-app
      - PKI_ADDRESS=http://pki-main:8080
      - REPO_ADDRESS=http://repo:9000
      - REPO_API_KEY=foobar
    networks:
      - app-net
    volumes:
      - ./tmp/app:/app/data

  api:
    image: ghcr.io/wirepact/demo-applications/basic-auth-api:latest
    environment:
      - PORT=9001
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=supersecret
    networks:
      - app-net

  envoy-api:
    image: envoyproxy/envoy:v1.23-latest
    depends_on:
      - provider-api
    command: envoy -c /etc/envoy/envoy.yaml --component-log-level connection:debug,ext_authz:debug
    volumes:
      - ./hack/envoy-config.api.yaml:/etc/envoy/envoy.yaml:ro
      - ./tmp/api:/certs
    networks:
      - app-net

  translator-api:
    image: ghcr.io/wirepact/k8s-basic-auth-translator:2.0.31
    depends_on:
      - pki-main
    volumes:
      - ./hack/test-repository.csv:/test-repository.csv:ro
    environment:
      - PKI_ADDRESS=http://pki-main:8080
      - NAME=translator-api
      - DEBUG=true
      - CSV_PATH=/test-repository.csv
    networks:
      - app-net

  provider-api:
    image: ghcr.io/wirepact/contract-provider:1-latest
    user: root
    depends_on:
      - repo
      - pki-main
    environment:
      - DEBUG=true
      - COMMON_NAME=envoy-api
      - PKI_ADDRESS=http://pki-main:8080
      - REPO_ADDRESS=http://repo:9000
      - REPO_API_KEY=foobar
    networks:
      - app-net
    volumes:
      - ./tmp/api:/app/data

networks:
  app-net:
    driver: bridge
